name: Auto-Sync Repository

on:
  schedule:
    - cron: '*/5 * * * *'  # Каждые 5 минут
  workflow_dispatch:

jobs:
  sync-repo:
    runs-on: [self-hosted, linux, x64]
    
    steps:
      - name: Setup SSH Environment
        run: |
          # Добавляем приватный ключ
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > /home/kind/.ssh/github_actions_new.pub
          chmod 600 /home/kind/.ssh/github_actions_new.pub
          
          # Добавляем GitHub в known_hosts
          echo "github.com ssh-github_actions AAAAC3NzaC1lZDI1NTE5AAAAII9LgFJt1q9Z5JQ7Jg7Jg7Jg7Jg7Jg7Jg7Jg7Jg7Jg" >> ~/.ssh/known_hosts
          
          # Тестируем подключение
          ssh -T git@github.com || true

      - name: Configure Git
        run: |
          git config --global --add safe.directory /home/kind/ansible-cluster
          git config --global user.name "Auto-Sync-Bot"
          git config --global user.email "auto-sync@example.com"
          git config --global core.sshCommand "ssh -i /home/kind/.ssh/github_actions_new -o IdentitiesOnly=yes"

      - name: Sync Repository
        run: |
          cd /home/kind/ansible-cluster
          
          # Принудительно обновляем ветку
          git remote set-url origin git@github.com:LovemeTrue/Ansible.git
          git fetch origin
          git reset --hard origin/main
          
          # Проверяем и коммитим изменения
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Auto-sync: $(date '+%Y-%m-%d %H:%M:%S')"
            git push origin main
          else
            echo "Нет изменений для коммита"
          fi
