
name: Pull from Server via HTTPS with AutoCreds

on:
  schedule:
    - cron: '*/700 * * * *'  # Каждые 700 минут 
  workflow_dispatch:

jobs:
  pull-from-server:
    runs-on: [self-hosted, linux, x64]
    steps:
  
      - name: Changing Permission Policies
        run: |
          sudo chown -R kind:kind /home/kind/ansible-cluster
          sudo chmod -R ug+rwX /home/kind/ansible-cluster/.git
          
      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/github_actions
          chmod 600 ~/.ssh/github_actions
          cd /home/kind/ansible-cluster
          git remote set-url origin git@github.com:LovemeTrue/Ansible.git

      - name: Sync repository
        run: |
          git config --global --add safe.directory /home/kind/ansible-cluster
          cd /home/kind/ansible-cluster
          git pull origin main || true
          git add .
          git commit -m "Auto-sync $(date '+%Y-%m-%d %H:%M:%S')" || true
          git push origin main
