name: Pull and Push from Local via SSH

on:
  schedule:
    - cron: '*/30 * * * *'  # каждые 30 минут
  workflow_dispatch:        # ручной запуск

jobs:
  sync-from-local:
    runs-on: ubuntu-latest

    steps:
      - name: Start SSH Agent and Add Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Clone repo from local server
        run: |
          rm -rf local-copy
          git clone kind@192.168.29.24:/home/kind/k8s-cluster-config.git local-copy

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push to GitHub via SSH
        run: |
          cd local-copy
          git remote set-url origin git@github.com:LovemeTrue/Ansible.git
          git push origin main
