name: Auto Commit and Push

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # Разрешает ручной запуск

jobs:
  auto-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add all files
        run: git add .

      - name: Commit changes
        run: |
          git commit -m "Auto-commit by GitHub Actions" || echo "No changes to commit"
          
      - name: Push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Используем сохранённый токен
        run: |
          git remote set-url origin "https://${GH_TOKEN}@github.com/LovemeTrue/Ansible.git"
          git push origin main
