name: Pull from Server via HTTPS

on:
  schedule:
    - cron: '*/300 * * * *'  # Каждые 5 минут (исправлено с */450)
  workflow_dispatch:

jobs:
  pull-from-server:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Configure Git credentials
        run: |
          git config --global credential.helper 'store --file ~/.git-credentials'
          echo "https://LovemeTrue:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
          chmod 600 ~/.git-credentials

      - name: Sync repository
        run: |
          git config --global --add safe.directory /home/kind/ansible-cluster
          cd /home/kind/ansible-cluster
          git pull origin main || true
          git add .
          git commit -m "Auto-sync $(date '+%Y-%m-%d %H:%M:%S')" || true
          git push origin main
