name: Pull and Push from Local Server

on:
  schedule:
    - cron: '*/5 * * * *'  # каждые 5 минут
  workflow_dispatch:

jobs:
  sync-from-local:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.LOCAL_SSH_KEY }}

      - name: Clone repo from local server
        run: |
          rm -rf local-copy
          git clone kind@192.168.29.24:/home/kind/ansible-cluster/k8s-cluster-config.git local-copy

      - name: Configure Git for push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push to GitHub (LovemeTrue/Ansible)
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd local-copy
          git remote set-url origin https://LovemeTrue:${GH_TOKEN}@github.com/LovemeTrue/Ansible.git
          git push origin main
