name: Pull from Server via HTTPS

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  pull-from-server:
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Pull from local repo
        run: |
          cd /home/kind/ansible-cluster
          git pull origin main || true
          git add .
          git commit -m "Auto-sync" || true
          git push origin main
